
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import DA.PaymentDA;
import DA.FoodOrderDA;
import DA.CustomerDA;
import Domain.Customer;
import Domain.FoodOrder;
import Domain.Payment;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BryanLee
 */
public class Sprint2 extends javax.swing.JFrame {

    /**
     * Creates new form Sprint2
     */
    PaymentDA paymentDA = new PaymentDA();
    CustomerDA customerDA = new CustomerDA();
    FoodOrderDA foodOrderDA = new FoodOrderDA();
    String receiptNo, custID;
    ResultSet rs;

    public Sprint2() {
        initComponents();
//        phoneNumberCB.addItem("012-3689296");
//        jtxName.setText("Lee Bryan");
//        jtxOrderID.setText("2001");
//        jtfPNumber.setText("012-3689296");
//        jtaAddress.setText("No 7, Jalan Serdang Kuala Lumpur");
        Fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phoneNumberCB = new javax.swing.JComboBox<>();
        lblOrderID = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfPNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        labelName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfReceiptNO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        phoneNumberCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberCBActionPerformed(evt);
            }
        });

        lblOrderID.setText("Receipt No");

        cancelButton.setText("Ok");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Address");

        jtaAddress.setColumns(20);
        jtaAddress.setRows(5);
        jScrollPane2.setViewportView(jtaAddress);

        labelName.setText("Name");

        jLabel5.setText("Phone Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumberCB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(labelName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancelButton))
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblOrderID)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfReceiptNO, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 36, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrderID)
                        .addComponent(jtfReceiptNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumberCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberCBActionPerformed
//        String orderID = (String) orderedID.getSelectedItem();
//        ArrayList<Payment> List = paymentDA.retrieveRecord(orderID);
//
//        try {
//            for (int a = 0; a < List.size(); a++) {
//                custID = List.get(a).getCustID();
//                //jtfPNumber.setText(custID);
//                rs = customerDA.selectPNumberAndAddress(custID);
//                while (rs.next()) {
//                    jtfPNumber.setText(rs.getString(1));
//                    jtaAddress.setText(rs.getString(2));
//                }
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Sprint2.class.getName()).log(Level.SEVERE, null, ex);
//        }
        String pNumber = (String) phoneNumberCB.getSelectedItem();
        ArrayList<Customer> list = customerDA.retrieveRecord(pNumber);

        for (int a = 0; a < list.size(); a++) {
            jtfName.setText(list.get(a).getCustName());
            jtfPNumber.setText(list.get(a).getpNumber());
            jtaAddress.setText(list.get(a).getAddress());
            custID = list.get(a).getCustID();
        }
        
        ArrayList<Payment> paymentList = paymentDA.retrieveRecord(custID);
        for (int i = 0; i < paymentList.size(); i++) {
            jtfReceiptNO.setText(Integer.toString(paymentList.get(i).getReceiptNo()));
        }
    }//GEN-LAST:event_phoneNumberCBActionPerformed

//    public void showOrderedTable(String orderID) throws SQLException {
    //        ArrayList<FoodOrder> List = foodOrderDA.retrieveRecord(orderID);
    //        DefaultTableModel model = (DefaultTableModel) orderedTable.getModel();
    //        Object[] col = new Object[2];
    //        for (int a = 0; a < List.size(); a++) {
    //            //row[0] = List.get(a).getFoodID();
    //            col[0] = List.get(a).getFoodName();
    //            col[1] = List.get(a).getQty();
    //
    //            model.addRow(col);
    //        }
    //    }
    private void Fillcombo() {
        try {
            ResultSet rs = paymentDA.selectNotDeliveredRecord();
            //ArrayList<Customer> liist = (ArrayList<Customer>) customerDA.selectPNumberAndAddress(rs.getString(1));
            while (rs.next()) {
                ResultSet rs2 = customerDA.selectPNumberAndAddress(rs.getString(1));
                while (rs2.next()) {
                    phoneNumberCB.addItem(rs2.getString(1));
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sprint2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sprint2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sprint2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sprint2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sprint2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPNumber;
    private javax.swing.JTextField jtfReceiptNO;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JComboBox<String> phoneNumberCB;
    // End of variables declaration//GEN-END:variables
}
